from __future__ import annotations

import csv
import logging
import os
import subprocess
import tempfile
import uuid
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

import boto3
from botocore.exceptions import ClientError
from jinja2 import Environment, FileSystemLoader, TemplateNotFound

from app.core.config import settings
from app.schemas.export_schemas import ExportFormat

logger = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent.parent / "templates" / "reports"
S3_EXPORT_PREFIX = "exports"
DOWNLOAD_URL_TTL_SECONDS = 3600  # 1 hour


class ExportServiceError(Exception):
    """Raised when the export service encounters an unrecoverable error."""


class ExportService:
    """
    Handles report generation for both PDF and CSV formats.

    PDF exports are generated by rendering a Jinja2 HTML template and piping
    the result through wkhtmltopdf.  CSV exports are written directly using
    the csv stdlib module and do not require any external binary.
    """

    def __init__(self) -> None:
        self._s3 = boto3.client(
            "s3",
            region_name=settings.AWS_REGION,
            aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
            aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
        )
        self._jinja_env = Environment(
            loader=FileSystemLoader(str(TEMPLATES_DIR)),
            autoescape=True,
        )

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def generate_report(
        self,
        *,
        project_data: Dict[str, Any],
        tasks: List[Dict[str, Any]],
        export_format: ExportFormat,
        report_title: str,
        template_name: str = "default",
        job_id: str,
    ) -> str:
        """
        Generate a report file and upload it to S3.

        Returns the S3 object key of the uploaded file.
        """
        if export_format == ExportFormat.csv:
            local_path = self._generate_csv(
                project_data=project_data,
                tasks=tasks,
                report_title=report_title,
                job_id=job_id,
            )
        else:
            local_path = self._generate_pdf(
                project_data=project_data,
                tasks=tasks,
                report_title=report_title,
                template_name=template_name,
                job_id=job_id,
            )

        try:
            s3_key = self._upload_to_s3(local_path=local_path, job_id=job_id, fmt=export_format)
        finally:
            # Always clean up temp file, even on upload failure
            try:
                os.unlink(local_path)
            except OSError:
                pass

        return s3_key

    def get_presigned_download_url(self, s3_key: str) -> tuple[str, datetime]:
        """
        Generate a pre-signed URL for the exported file.

        Returns (url, expiry_datetime).
        """
        try:
            url = self._s3.generate_presigned_url(
                "get_object",
                Params={"Bucket": settings.S3_EXPORTS_BUCKET, "Key": s3_key},
                ExpiresIn=DOWNLOAD_URL_TTL_SECONDS,
            )
        except ClientError as exc:
            logger.error("Failed to generate pre-signed URL for %s: %s", s3_key, exc)
            raise ExportServiceError("Could not generate download link") from exc

        expires_at = datetime.utcnow() + timedelta(seconds=DOWNLOAD_URL_TTL_SECONDS)
        return url, expires_at

    # ------------------------------------------------------------------
    # CSV generation
    # ------------------------------------------------------------------

    def _generate_csv(
        self,
        *,
        project_data: Dict[str, Any],
        tasks: List[Dict[str, Any]],
        report_title: str,
        job_id: str,
    ) -> str:
        tmp = tempfile.NamedTemporaryFile(
            delete=False,
            suffix=".csv",
            prefix=f"meridian_export_{job_id}_",
        )
        tmp.close()

        fieldnames = [
            "task_id",
            "title",
            "assignee",
            "status",
            "priority",
            "due_date",
            "created_at",
            "updated_at",
            "tags",
        ]

        with open(tmp.name, "w", newline="", encoding="utf-8") as fh:
            # Write report metadata header rows
            fh.write(f"# {report_title}\n")
            fh.write(f"# Project: {project_data.get('name', 'Unknown')}\n")
            fh.write(f"# Exported: {datetime.utcnow().isoformat()}Z\n")
            fh.write("#\n")

            writer = csv.DictWriter(fh, fieldnames=fieldnames, extrasaction="ignore")
            writer.writeheader()
            for task in tasks:
                writer.writerow({
                    "task_id": task.get("id", ""),
                    "title": task.get("title", ""),
                    "assignee": task.get("assignee_email", ""),
                    "status": task.get("status", ""),
                    "priority": task.get("priority", ""),
                    "due_date": task.get("due_date", ""),
                    "created_at": task.get("created_at", ""),
                    "updated_at": task.get("updated_at", ""),
                    "tags": ",".join(task.get("tags", [])),
                })

        logger.info("CSV report written to %s (%d tasks)", tmp.name, len(tasks))
        return tmp.name

    # ------------------------------------------------------------------
    # PDF generation
    # ------------------------------------------------------------------

    def _generate_pdf(
        self,
        *,
        project_data: Dict[str, Any],
        tasks: List[Dict[str, Any]],
        report_title: str,
        template_name: str,
        job_id: str,
    ) -> str:
        html_path = self._render_html_template(
            project_data=project_data,
            tasks=tasks,
            report_title=report_title,
            template_name=template_name,
            job_id=job_id,
        )

        pdf_tmp = tempfile.NamedTemporaryFile(
            delete=False,
            suffix=".pdf",
            prefix=f"meridian_export_{job_id}_",
        )
        pdf_tmp.close()
        pdf_path = pdf_tmp.name

        try:
            self._run_wkhtmltopdf(
                html_path=html_path,
                pdf_path=pdf_path,
                report_title=report_title,
            )
        finally:
            try:
                os.unlink(html_path)
            except OSError:
                pass

        return pdf_path

    def _render_html_template(
        self,
        *,
        project_data: Dict[str, Any],
        tasks: List[Dict[str, Any]],
        report_title: str,
        template_name: str,
        job_id: str,
    ) -> str:
        template_file = f"{template_name}.html"
        try:
            template = self._jinja_env.get_template(template_file)
        except TemplateNotFound:
            logger.warning(
                "Template '%s' not found, falling back to default", template_file
            )
            template = self._jinja_env.get_template("default.html")

        context = {
            "report_title": report_title,
            "project": project_data,
            "tasks": tasks,
            "exported_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            "task_count": len(tasks),
        }
        rendered_html = template.render(**context)

        html_tmp = tempfile.NamedTemporaryFile(
            delete=False,
            suffix=".html",
            prefix=f"meridian_tpl_{job_id}_",
            mode="w",
            encoding="utf-8",
        )
        html_tmp.write(rendered_html)
        html_tmp.close()
        return html_tmp.name

    def _run_wkhtmltopdf(
        self,
        *,
        html_path: str,
        pdf_path: str,
        report_title: str,
    ) -> None:
        """
        Invoke wkhtmltopdf to convert the rendered HTML report to PDF.

        Page title is passed via --title so it appears in the PDF metadata
        and print dialog.  We use shell=True here for simplicity so the
        title string (which may contain spaces) doesn't need extra quoting
        gymnastics when building the argument list.
        """
        wkhtmltopdf_bin = getattr(settings, "WKHTMLTOPDF_BIN", "wkhtmltopdf")

        cmd = (
            f"{wkhtmltopdf_bin} "
            f"--quiet "
            f"--page-size A4 "
            f"--margin-top 15mm "
            f"--margin-bottom 15mm "
            f"--margin-left 12mm "
            f"--margin-right 12mm "
            f"--title \"{report_title}\" "
            f"{html_path} "
            f"{pdf_path}"
        )

        logger.debug("Running wkhtmltopdf: %s", cmd)

        result = subprocess.run(
            cmd,
            shell=True,
            capture_output=True,
            text=True,
            timeout=120,
        )

        if result.returncode != 0:
            logger.error(
                "wkhtmltopdf exited with code %d: %s",
                result.returncode,
                result.stderr,
            )
            raise ExportServiceError(
                f"PDF generation failed (exit {result.returncode}): {result.stderr[:200]}"
            )

    # ------------------------------------------------------------------
    # S3 helpers
    # ------------------------------------------------------------------

    def _upload_to_s3(
        self,
        *,
        local_path: str,
        job_id: str,
        fmt: ExportFormat,
    ) -> str:
        ext = "pdf" if fmt == ExportFormat.pdf else "csv"
        s3_key = f"{S3_EXPORT_PREFIX}/{job_id}/report.{ext}"

        content_type = "application/pdf" if fmt == ExportFormat.pdf else "text/csv"

        try:
            self._s3.upload_file(
                Filename=local_path,
                Bucket=settings.S3_EXPORTS_BUCKET,
                Key=s3_key,
                ExtraArgs={
                    "ContentType": content_type,
                    "ServerSideEncryption": "AES256",
                },
            )
        except ClientError as exc:
            logger.error("S3 upload failed for job %s: %s", job_id, exc)
            raise ExportServiceError("Failed to upload report to storage") from exc

        logger.info("Uploaded export to s3://%s/%s", settings.S3_EXPORTS_BUCKET, s3_key)
        return s3_key
