from __future__ import annotations

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.orm import Session

from app.auth.dependencies import get_current_user, require_project_member
from app.db.session import get_db
from app.models.activity_event import EventType
from app.models.user import User
from app.schemas.activity import ActivityFeedPage, ActivityFeedParams
from app.services.activity_service import ActivityService

router = APIRouter(
    prefix="/projects/{project_id}/activity",
    tags=["activity"],
)

_MAX_PAGE_SIZE = 50
_DEFAULT_PAGE_SIZE = 25


@router.get(
    "",
    response_model=ActivityFeedPage,
    summary="List recent activity for a project",
    description=(
        "Returns a reverse-chronological stream of activity events for the "
        "given project. Supports cursor-based pagination for infinite scroll, "
        "optional filtering by event type, actor, and date range."
    ),
)
def get_project_activity(
    project_id: UUID,
    # --- pagination ---
    limit: int = Query(
        default=_DEFAULT_PAGE_SIZE,
        ge=1,
        le=_MAX_PAGE_SIZE,
        description="Number of events per page (1–50).",
    ),
    cursor: Optional[str] = Query(
        default=None,
        description="Opaque pagination cursor returned by the previous response.",
    ),
    # --- filters ---
    event_type: Optional[List[EventType]] = Query(
        default=None,
        alias="event_type",
        description=(
            "Restrict results to one or more event types. "
            "Repeat the parameter to pass multiple values: "
            "?event_type=task_created&event_type=task_updated"
        ),
    ),
    actor_id: Optional[UUID] = Query(
        default=None,
        description="Return only events generated by this user.",
    ),
    after: Optional[datetime] = Query(
        default=None,
        description="Exclude events at or before this ISO-8601 timestamp.",
    ),
    before: Optional[datetime] = Query(
        default=None,
        description="Exclude events at or after this ISO-8601 timestamp.",
    ),
    # --- dependencies ---
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
    _membership = Depends(require_project_member),
) -> ActivityFeedPage:
    """
    Retrieve a page of activity events for *project_id*.

    The caller must be an authenticated member of the project's tenant.  Tenant
    isolation is enforced inside the service layer via the tenant_id carried on
    *current_user*.

    **Pagination**

    Pass the ``next_cursor`` value from one response as the ``cursor`` query
    parameter of the next request to advance through the feed.  A ``null``
    ``next_cursor`` means there are no further events matching the current
    filter set.

    **Filtering**

    Filters are ANDed together.  The ``after`` / ``before`` window is
    exclusive on both ends.  Date range filters are ignored on pages beyond
    the first (i.e., when a cursor is present) because the cursor already
    anchors the result window.
    """
    if after is not None and before is not None and after >= before:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="'after' must be strictly earlier than 'before'.",
        )

    service = ActivityService(db=db)

    try:
        page = service.get_project_feed(
            project_id=project_id,
            tenant_id=current_user.tenant_id,
            limit=limit,
            cursor=cursor,
            event_types=event_type,
            actor_id=actor_id,
            after=after,
            before=before,
        )
    except ValueError as exc:
        # Malformed cursor or invalid filter value surfaced from service layer.
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc

    return page
